### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by sechan-hwang** [sh951011/Korean-Speech-Recognition#3]
아래 오류가 발생합니다..
타입이 안맞는거 같아요~~

[2020-03-11 08:40:53,792 train.py:121 - <module>()] start
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    teacher_forcing_ratio = hparams.teacher_forcing
  File "/schwang/stt_kai/Korean-Speech-Recognition_20200310/package/trainer.py", line 58, in supervised_train
    y_hat, logit = model(feats, targets, teacher_forcing_ratio=teacher_forcing_ratio)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/schwang/stt_kai/Korean-Speech-Recognition_20200310/models/listenAttendSpell.py", line 42, in forward
    listener_outputs = self.listener(feats)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/schwang/stt_kai/Korean-Speech-Recognition_20200310/models/listener.py", line 175, in forward
    middle_output = self.middle_rnn(bottom_output)
  File "/root/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/schwang/stt_kai/Korean-Speech-Recognition_20200310/models/listener.py", line 50, in forward
    batch_size = inputs.size(0)
AttributeError: 'tuple' object has no attribute 'size'

**Comment by sh951011** [comment]
현재 업데이트 되어 있는 코드로 실행하신 건가요??  
제가 돌리는 코드는 문제없이 진행되고 있는 상황입니다.
한번 확인 부탁드려요.

**Comment by sh951011** [comment]
저도 현재 올려져 있는 코드로 확인을 한번 해보겠습니다.

**Comment by sechan-hwang** [comment]
내 아침에 clone 다시해서 실행한 결과에요.

**Comment by sh951011** [comment]
지금 에러가 나는 부분이 있는데 1시간 내로 수정 가능할 것 같습니다. 잠시만 기다려주세요 ㅎㅎ

**Comment by sechan-hwang** [comment]
다행이네요.^^ 천천히 하셔도 됩니다.^^

**Comment by sh951011** [comment]
![image](https://user-images.githubusercontent.com/42150335/76408671-a7560000-63d0-11ea-9e53-88cc99192f25.png)
에러 해결하고 잘 동작하는거 확인했습니다. ㅎㅎ 
모델쪽 수정하다가 실수를 했었네요 감사합니다.

그리고 데이터 아웃라이어 관련하여 처리를 조금 추가했습니다.
https://github.com/sh951011/Korean-Speech-Recognition/wiki/Data-Analysis
참고하시면 좋을 것 같습니다.

감사합니다.

**Comment by sechan-hwang** [comment]
학습이 진행됩니다. 수정 감사합니다. 
아웃라이어 관련해서는 참고해 보겠습니다.
